name: Docker Image Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    name: Scan Docker Image
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker Image
        run: |
          docker buildx build -f app.dockerfile -t my-image:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-image:latest'
          format: 'table'
          exit-code: 1
          severity: 'CRITICAL,HIGH'

      - name: Run Custom Action
        uses: ./.github/actions/performance-test  # Reference the action
